### ISSUE TITLE
driver broken on 4.19.23  (gcc 8.2.0)

### ISSUE THREAD

**Issue by klslz** [SatoruKawase/I-Sabre-K2M#4]
The RPI kernel was stepped up officially to 4.19.x recently.

I tried to integrate the driver into the kernel:

*******************************************************

sound/soc/bcm/i-sabre-k2m.c: In function 'snd_rpi_i_sabre_k2m_init':
sound/soc/bcm/i-sabre-k2m.c:33:35: error: 'struct snd_soc_pcm_runtime' has no member named 'codec'
  struct snd_soc_codec *codec = rtd->codec;
                                   ^~
sound/soc/bcm/i-sabre-k2m.c:37:10: error: implicit declaration of function 'snd_soc_read'; did you mean 'snd_soc_cnew'? [-Werror=implicit-function-declaration]
  value = snd_soc_read(codec, ISABRECODEC_REG_01);
          ^~~~~~~~~~~~
          snd_soc_cnew
In file included from ./include/sound/core.h:25,
                 from sound/soc/bcm/i-sabre-k2m.c:23:
sound/soc/bcm/i-sabre-k2m.c:38:16: error: dereferencing pointer to incomplete type 'struct snd_soc_codec'
  dev_info(codec->dev, "Audiophonics Device ID : %02X\n", value);
                ^~
./include/linux/device.h:1424:12: note: in definition of macro 'dev_info'
  _dev_info(dev, dev_fmt(fmt), ##__VA_ARGS__)
            ^~~
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:303: sound/soc/bcm/i-sabre-k2m.o] Error 1
make[2]: *** [scripts/Makefile.build:544: sound/soc/bcm] Error 2
make[1]: *** [scripts/Makefile.build:544: sound/soc] Error 2
make: *** [Makefile:1047: sound] Error 2
make: *** Waiting for unfinished jobs....

***********************************************

The driver seems to be broken.

Is the driver still maintained?

**Comment by audiophonics** [comment]
snd_soc_codec disappeared from snd_soc_pcm_runtime for kernel > 4.17
snd_soc_read too

So yes the driver will only work until kernel 4.17, we are looking how to fix it.

**Comment by klslz** [comment]
Yep.
They use something like:

struct snd_soc_component *component =

instead of snd_soc_codec

and

snd_soc_component_read32

instead of

snd_soc_read

as far as I've seen.

**Comment by audiophonics** [comment]
Thanks, we updated our driver version here : 

https://github.com/audiophonics/I-Sabre_9038Q2M

It's ok on 4.19.25

**Comment by klslz** [comment]
It wasn't OK on the first commit. ;)

sound/soc/bcm/i-sabre-q2m.c:46:2: error: expected ';' before 'return'

I guess  you fixed it now. Just trying it once more.

**Comment by audiophonics** [comment]
Yes it's ok now, I made this mistake replacing snd_soc_read with snd_soc_component_read32
I didn't changed snd_soc_read on the first commit because there was no error, but finally done it.

**Comment by klslz** [comment]
Just tried it. It compiles OK now.
However. No sound.
Everything looks OK on /proc/asound/... while playing back.
At the end of the track I experience loud scratching that almost killed my speakers.

Please check! I also do some more debugging. Perhaps I have a problem with my setup,
since I integrate the driver fully into the kernel sources.

**Comment by audiophonics** [comment]
I tested it with 16/44 without problems, and DSD... maybe a board problem ?
The board was working on a 4.14 kernel ?

**Comment by klslz** [comment]
It used to work. But I havn't been using it for quite a while.

The blue LED keeps flashing all the time btw.

I 'll also have a look at the PS.

**Comment by audiophonics** [comment]
Blue led flashing is normal.
Please contact us from your account -> RMA on our website to solve this issue.

**Comment by klslz** [comment]
Just realized. I probably have the old 9028 DAC version.
